### ISSUE TITLE
Is it .NET Core ready?

### ISSUE THREAD

**Issue by SuperJMN** [AlbedoOrg/Albedo#94]
My project (OmniXAML https://github.com/SuperJMN/OmniXAML/) does make use of reflection quite intensively, so I thought about using this library. The problem is that right now I'm porting it to .NET Core.

Is Albedo usable by .NET Core libraries using .NET Standard?

**Comment by ploeh** [comment]
It's not currently available for .NET Core, but I'm open to it :smile:

**Comment by SuperJMN** [comment]
I'm really looking forward to it! Thanks for the quick response, Super Master Mark!

**Comment by roarwrecker** [comment]
It seems that this is not possible right now. Albedo references code in the System.Reflection and System.Type namespaces which has not been ported to .Net Standard 1.6 or .Net Core 1.1.

I have analyzed the Albedo DLL using the [.Net Portability Analyzer](https://visualstudiogallery.msdn.microsoft.com/1177943e-cfb7-4822-a8a6-e56c7905292b). I have attached  the result which tells us that the required changes will be done in .Net Standard 2.0 and .Net Core 2.0.

![portability_summary](https://cloud.githubusercontent.com/assets/2168384/23379892/ef079d66-fd38-11e6-86f0-f5891ed4f893.png)

**Comment by zvirja** [comment]
It's already implemented in master. We target .NET Standard 2.0 as it contains all the API we need.
Will be released soon after all the preparations are done.

**Comment by zvirja** [comment]
Good news everyone! 🎉🌟🎆 

I've just published v2 that supports .NET Standard 2.0. Be aware of the [announcement](https://github.com/AlbedoOrg/Albedo#announcement) in ReadMe.

**Comment by moodmosaic** [comment]
Great job, @zvirja.
