### ISSUE TITLE
Change the default namespace

### ISSUE THREAD

**Issue by zvirja** [AlbedoOrg/Albedo#97]
To reflect the change of the Governance model I'd like to adjust the default namespace and trim the "Ploeh" namespace prefix. That should perfectly fit the [SemVer](http://semver.org) as we are releasing the major version. We made a [similar decision](https://github.com/AutoFixture/AutoFixture/issues/745) in AutoFixture project, so I don't see too much issues with that.

@moodmosaic @adamchester @jwChung let me know if you have any concerns. Also confirm that you are fine, so I could proceed with that change and the v2 release.

**Comment by moodmosaic** [comment]
Go for it 👍

**Comment by adamchester** [comment]
Go for it

Also, sorry again I haven’t responded to all issues where I’m mentioned, still very busy :sadface:

**Comment by jwChung** [comment]
Go for it.
